<?php
class FinalprojectSidebarButtonModuleFrontController extends ModuleFrontController{

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub

        // Y la lógica
    }


    // Y la lógica
}